$(document).ready(() => {
	
	$('#Html-css').on('click', () => {
        $('#projetos').html('<div id="carousel" class="carousel carousel-dark slide carousel-fade" data-bs-ride="false"><div class="carousel-indicators"><button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="3" aria-label="Slide 4"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="4" aria-label="Slide 5"></button></div><div class="carousel-inner"><div class="carousel-item active"><a href="https://github.com/Zoberobe/Css-Basic/tree/main/projetoTec" target="_blank"><img src="imagens/img-projetos/html-css/tec-blog.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/css-advanced" target="_blank" ><img src="imagens/img-projetos/html-css/noticias.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/css-advanced" target="_blank"><img src="imagens/img-projetos/html-css/museu.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/projeto-finans" target="_blank"><img src="imagens/img-projetos/html-css/finans.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/spotify-clone" target="_blank"><img src="imagens/img-projetos/html-css/spotify.png" class="d-block w-100"></a></div><button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button><button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next</span></button></div></div>')
	})

	$('#Html-Css-Javascript').on('click', () => {
        $('#projetos').html('<div id="carousel" class="carousel carousel-dark slide carousel-fade" data-bs-ride="false"><div class="carousel-indicators"><button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button></div><div class="carousel-inner"><div class="carousel-item active"><a href="https://zoberobe.github.io/Calculadora-Javascript/" target="_blank"><img src="imagens/img-projetos/javascript/calculadora.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://zoberobe.github.io/OrcamentoPessoal/" target="_blank" ><img src="imagens/img-projetos/javascript/despesa.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://zoberobe.github.io/DinDin/" target="_blank" ><img src="imagens/img-projetos/javascript/din-din.png" class="d-block w-100"></a></div><button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button><button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next</span></button></div>')

	})

    $('#Html-Css-Php-Mysql').on('click', () => {
		$('#projetos').html('<div id="carousel" class="carousel carousel-dark slide carousel-fade" data-bs-ride="false"><div class="carousel-indicators"><button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="3" aria-label="Slide 4"></button><button type="button" data-bs-target="#carousel" data-bs-slide-to="4" aria-label="Slide 5"></button></div><div class="carousel-inner"><div class="carousel-item active"><a href="https://github.com/Zoberobe/Help-desk" target="_blank"><img src="imagens/img-projetos/php/help-desk.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/CRUD-Lista" target="_blank" ><img src="imagens/img-projetos/php/lista-tarefas.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/send_mail" target="_blank"><img src="imagens/img-projetos/php/send-email.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/dashboard" target="_blank" ><img src="imagens/img-projetos/php/dashboard.png" class="d-block w-100"></a></div><div class="carousel-item"><a href="https://github.com/Zoberobe/Twitter-Clone" target="_blank" ><img src="imagens/img-projetos/php/twitter.png" class="d-block w-100"></a></div><button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button><button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next</span></button></div></div>')
	})


})
